site_name: erln8
theme: cosmo
pages:
- Home: index.md
- Installation: installation.md
- Quickstart: quickstart.md
- erln8 Usage: usage.md
- reo Usage: usage.md
- License &amp; Contributing: contributing.md
